//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace AppFinanciera.Models.DTO
{


    public partial class CuentaUsuario
    {

        [XmlElement(ElementName ="Id")]
        public int Id { get; set; }
        public string NombreCuenta { get; set; }
        public string Descripcion { get; set; }
        public string Moneda { get; set; }
        public decimal BalanceInicial { get; set; }
        public decimal BalanceActual { get; set; }
        public string Tags { get; set; }
        public int UsuarioExtraInfoId { get; set; }
    
       
    }
}
