//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFinanciera.Models.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioExtraInfo
    {

    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Apodo { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public bool EsActivo { get; set; }
    
       public string Pass { get; set; }
    }
}
