//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFinanciera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaUsuario()
        {
            this.MovimientoCuentas = new HashSet<MovimientoCuentas>();
        }
    
        public int Id { get; set; }
        public string NombreCuenta { get; set; }
        public string Descripcion { get; set; }
        public string Moneda { get; set; }
        public decimal BalanceInicial { get; set; }
        public decimal BalanceActual { get; set; }
        public string Tags { get; set; }
        public int UsuarioExtraInfoId { get; set; }
    
        public virtual UsuarioExtraInfo UsuarioExtraInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoCuentas> MovimientoCuentas { get; set; }
    }
}
