//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFinanciera.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelFinancieraContainer : DbContext
    {
        public ModelFinancieraContainer()
            : base("name=ModelFinancieraContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UsuarioExtraInfo> Usuarios { get; set; }
        public virtual DbSet<CuentaUsuario> CuentaUsuarios { get; set; }
        public virtual DbSet<MovimientoCuentas> MovimientoCuentas { get; set; }
        public virtual DbSet<TipoDeGasto> TipoDeGastos { get; set; }
    }
}
