//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFinanciera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoCuentas
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Comentarios { get; set; }
        public decimal Monto { get; set; }
        public int TipoDeGastoId { get; set; }
        public int CuentaUsuarioId { get; set; }
    
        public virtual TipoDeGasto TipoDeGasto { get; set; }
        public virtual CuentaUsuario CuentaUsuario { get; set; }
    }
}
